name: Get Data From Static YAML File

on:
    workflow_dispatch:

jobs:
    get_data_from_static_yaml_file:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                    python-version: '3.x'

            - name: Install shyaml
              run: pip install shyaml

            - name: Get Data From Static YAML File and set it as ENV
              id: get_data_from_static_yaml_file
              # Read one time app.yml, gather the data, and save them
              run: |
                    NAME=$(cat app.yml | shyaml get-value name)
                    VERSION=$(cat app.yml | shyaml get-value version)
                    
                    echo "NAME=$NAME" >> $GITHUB_ENV
                    echo "VERSION=$VERSION" >> $GITHUB_ENV
            

            - name: Print ENVs
              run: |
                    echo "Name: $NAME"
                    echo "Version: $VERSION"
